# Generated by Django 5.0.1 on 2025-01-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_user_alter_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verification_token",
        ),
    ]
